### PR TITLE
Generate a .tag file and cross-link

### PR DESCRIPTION
**Pull request by dkfellows**
Will use the tag file from `spinnaker_tools` if it can get it. Have tested that locally. Being unable to get the dependency tag file is non-fatal as there's a fallback.

### CODE REVIEW

**Comment by dkfellows** [comment]
Note that the fallback tagfile does not include any of the symbols, but rather just enough that the build doesn't error.

**Review by rowleya — APPROVED** [review]
I'm probably going to have to update the install instructions on Windows, but OK

**Comment by dkfellows** [comment]
I'm hoping that users should only need wget if doing `make doxygen` while expecting to get properly interlinked docs out of the end. End users should be able to usually avoid building documentation trees at all.

**Comment by dkfellows** [comment]
Doxygen itself is a bigger requirement on Windows than wget…

**Comment by rowleya** [comment]
Yes true enough!

**Pull request merged**
